version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./client
    ports:
      - 5173:5173
    environment:
      - API_URL=http://localhost:5000

    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/packege-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    build: ./server
    ports:
      - 5000:5000
    environment:
      - PORT=5000

    develop:
      watch:
        - path: ./server/venv
          action: rebuild
        - path: ./server
          target: /app
          action: sync
